# Generated by Django 2.0.4 on 2018-05-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Measurment time.')),
                ('temperature', models.IntegerField(verbose_name='Temperature in Celsius.')),
                ('humidity', models.IntegerField(verbose_name='Humidity in %.')),
            ],
        ),
    ]
