# Generated by Django 2.0.4 on 2018-05-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'temperature entry', 'verbose_name_plural': 'temperature entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='humidity',
            field=models.FloatField(verbose_name='Humidity in %.'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='temperature',
            field=models.FloatField(verbose_name='Temperature in Celsius.'),
        ),
    ]
