# Generated by Django 2.1.2 on 2018-11-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('temperature', '0002_auto_20180513_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='device_id',
            field=models.CharField(default='raspberry_pi', max_length=100, verbose_name='device ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='humidity',
            field=models.FloatField(verbose_name='humidity in %.'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='temperature',
            field=models.FloatField(verbose_name='temperature in Celsius.'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='measurement time.'),
        ),
    ]
