# Generated by Django 2.1.2 on 2018-12-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("temperature", "0002_auto_20181202_1651")]

    operations = [
        migrations.AddField(
            model_name="measurementdevice", name="active", field=models.BooleanField(default=True)
        )
    ]
