# Generated by Django 2.1.2 on 2018-11-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('temperature', '0003_auto_20181125_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementDevice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='device ID')),
                ('name', models.CharField(max_length=100, verbose_name='device name')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='room name')),
                ('devices', models.ManyToManyField(to='temperature.MeasurementDevice')),
            ],
        ),
    ]
