# Generated by Django 2.1.2 on 2018-11-25 20:57

import django.db.models.deletion
from django.db import migrations, models


def create_default_device(apps, schema_editor):
    MeasurementDevice = apps.get_model('temperature', 'MeasurementDevice')
    try:
        MeasurementDevice.objects.create(id='raspberry_pi', name='Ob\u00fdva\u010dka (Raspberry Pi)')
    except:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('temperature', '0004_measurementdevice_room'),
    ]

    operations = [
        migrations.RunPython(create_default_device),
        migrations.AlterField(
            model_name='entry',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temperature.MeasurementDevice'),
        ),
    ]
