# Generated by Django 2.1.2 on 2018-12-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("temperature", "0004_auto_20181208_1523")]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={
                "ordering": ("-time",),
                "verbose_name": "temperature entry",
                "verbose_name_plural": "temperature entries",
            },
        ),
        migrations.AlterField(
            model_name="entry",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="measurement time"
            ),
        ),
    ]
