# Generated by Django 2.1.2 on 2018-11-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('temperature', '0005_auto_20181125_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4',
                                               verbose_name='device IP address'),
        ),
        migrations.AddField(
            model_name='measurementdevice',
            name='port',
            field=models.IntegerField(blank=True, default=80, null=True, verbose_name='device port'),
        ),
    ]
