# Generated by Django 2.2.1 on 2019-06-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("temperature", "0006_auto_20181208_1634")]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={
                "verbose_name": "temperature entry",
                "verbose_name_plural": "temperature entries",
            },
        )
    ]
