# Generated by Django 2.1.2 on 2018-11-25 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('temperature', '0006_auto_20181125_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='device_id',
            new_name='device',
        ),
    ]
