repos:
  - repo: https://github.com/python/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: local
    hooks:
      -   id: build-frontend
          name: Build production app.js
          entry: ./build_frontend.py
          language: script
          pass_filenames: false
          files: \.jsx?$