version: "3.7"

x-pi-control: &pi-control
  build:
    context: .
    dockerfile: ./docker/dev/Dockerfile
  image: mhozza/pi-control:dev-latest
  volumes:
    - ./pi_control:/web
    - node_modules:/web/home/js/node_modules
    - ${CPU_TEMPERATURE_FILE-./docker/shared/fake_cpu_temperature.txt}:/host_sys/temp:ro
  environment:
    - DB_BACKEND=django.db.backends.postgresql
    - DB_NAME=pi_control
    - DB_USER=pi_control
    - DB_HOST=db
    - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    - CPU_TEMPERATURE_FILE=/host_sys/temp
    - SERVER_NAME=malina
    - DEFAULT_FROM_EMAIL
    - EMAIL_HOST
    - EMAIL_PORT
    - EMAIL_HOST_USER
    - EMAIL_HOST_PASSWORD
    - EMAIL_USE_TLS

services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pi_control
      - POSTGRES_DB=pi_control
  rabbitmq:
    image: rabbitmq
  web:
    <<: *pi-control
    ports:
      - "8000:8000"
    depends_on:
      - db
  celery:
    <<: *pi-control
    command: watchmedo auto-restart --directory=/web --pattern=*.py --recursive -- celery -A pi_control worker -l info --pidfile="/tmp/celeryd.pid"
    depends_on:
      - rabbitmq
      - db
  celerybeat:
    <<: *pi-control
    command: celery -A pi_control beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile="/tmp/celerybeet.pid"
    depends_on:
      - rabbitmq
      - db
  webpack:
    <<: *pi-control
    command: npm run --prefix=/web/home/js dev

volumes:
  db_data:
  node_modules:
