version: '3.7'

x-pi-control: &pi-control
  image: mhozza/pi-control:latest
  volumes:
    - ${CPU_TEMPERATURE_FILE-./docker/shared/fake_cpu_temperature.txt}:/sys/class/thermal/thermal_zone0/temp
  devices:
    - ${TEMPERATURE_SENSOR_DEVICE-/dev/zero}:/dev/i2c-1
  environment:
    - DB_BACKEND=django.db.backends.postgresql
    - DB_NAME=pi_control
    - DB_USER=pi_control
    - DB_HOST=db
    - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    - CPU_TEMPERATURE_FILE=/sys/class/thermal/thermal_zone0/temp

services:
  web:
    <<: *pi-control
    ports:
      - "${PORT-8000}:80"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pi_control
      - POSTGRES_DB=pi_control
  rabbitmq:
    image: rabbitmq
  celery:
    <<: *pi-control
    command: celery -A pi_control worker -l debug
    depends_on:
      - rabbitmq
      - db
  celerybeat:
    <<: *pi-control
    command: celery -A pi_control beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - rabbitmq
      - db

volumes:
  db_data:
    