DEFAULT_HUMIDITY_HIGH = 50
DEFAULT_HUMIDITY_LOW = 30
DEFAULT_TEMPERATURE_HIGH = 25
DEFAULT_TEMPERATURE_LOW = 21
DEFAULT_DEVICE = 'raspberry_pi'

NOTIFICATION_GROUP_TEMPERATURE_HIGH = 'all'
NOTIFICATION_GROUP_TEMPERATURE_LOW = 'all'
NOTIFICATION_TTL = 60 * 15  # 15 Min.
