name: Docker Image CI

on: [push]

jobs:
  #build_prod:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v1
  #  - name: Build the Docker image
  #    run: docker build . --file docker/prod/Dockerfile --tag mhozza/pi-control:$(date +%s)
  build_dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # Cache docker layers
    - uses: jpribyl/action-docker-layer-caching@v0.1.1
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    - name: Build the dev Docker image
      run: docker build . --file docker/dev/Dockerfile
